# Generated by Django 3.1.3 on 2020-11-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='label',
            field=models.CharField(choices=[('In Progress', 'primary'), ('Pending', 'secondary'), ('Completed', 'success')], default='Pending', max_length=20),
        ),
    ]
